Add splash window
git-svn-id: file:///.data/svn_convert/svn@153 f7a67266-ba00-4dfb-90a2-3eec4ba07b7d

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1554,7 +1554,7 @@ fi
 
 # Define the identity of the package.
 PACKAGE=sim
-VERSION=0.7
+VERSION=0.1
 
 cat >>confdefs.h <<EOF
 #define PACKAGE "$PACKAGE"
@@ -21569,6 +21569,8 @@ done
 
 ac_config_files="$ac_config_files ./Makefile"
 
+ac_config_files="$ac_config_files pict/Makefile"
+
 ac_config_files="$ac_config_files po/Makefile"
 
 ac_config_files="$ac_config_files sim/Makefile"
@@ -21662,7 +21664,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:21665: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:21667: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -21838,7 +21840,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:21841: error: ambiguous option: $1
+    { { echo "$as_me:21843: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -21857,7 +21859,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:21860: error: unrecognized option: $1
+  -*) { { echo "$as_me:21862: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -21903,6 +21905,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "./Makefile" ) CONFIG_FILES="$CONFIG_FILES ./Makefile" ;;
+  "pict/Makefile" ) CONFIG_FILES="$CONFIG_FILES pict/Makefile" ;;
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
   "sim/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/Makefile" ;;
   "sim/libicq/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/libicq/Makefile" ;;
@@ -21912,7 +21915,7 @@ do
   "sounds/Makefile" ) CONFIG_FILES="$CONFIG_FILES sounds/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:21915: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:21918: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -22266,7 +22269,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:22269: creating $ac_file" >&5
+    { echo "$as_me:22272: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -22284,7 +22287,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22287: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22290: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22297,7 +22300,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22300: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22303: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22358,7 +22361,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:22361: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:22364: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -22369,7 +22372,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22372: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22375: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22382,7 +22385,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22385: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22388: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22499,7 +22502,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:22502: $ac_file is unchanged" >&5
+      { echo "$as_me:22505: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
