Makefile changed add italian translation
git-svn-id: file:///.data/svn_convert/svn@179 f7a67266-ba00-4dfb-90a2-3eec4ba07b7d

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -21763,6 +21763,16 @@ cat >>confdefs.h <<EOF
 #define PREFIX "$prefix"
 EOF
 
+if test "$WITH_OPENSSL" = "no"; then
+  echo ""
+  echo "OpenSSL support is not available.  SIM will not be able to"
+  echo "establish secure communication channels. This is not required"
+  echo "for proper function (i.e. it is optional). If you really desire this"
+  echo "functionality then install OpenSSL (libraries and headers) and"
+  echo "rebuild SIM.  OpenSSL can be found at http://www.openssl.org"
+  echo "or as RPM from your local distribution site."
+fi
+
 DO_NOT_COMPILE="$DO_NOT_COMPILE CVS debian bsd-port admin"
 
 if test ! -s $srcdir/subdirs; then
@@ -21781,7 +21791,7 @@ else
 fi
 
 for i in $ac_topsubdirs; do
-  echo "$as_me:21784: checking if $i should be compiled" >&5
+  echo "$as_me:21794: checking if $i should be compiled" >&5
 echo $ECHO_N "checking if $i should be compiled... $ECHO_C" >&6
   if test -d $srcdir/$i; then
     install_it="yes"
@@ -21793,7 +21803,7 @@ echo $ECHO_N "checking if $i should be compiled... $ECHO_C" >&6
   else
     install_it="no"
   fi
-  echo "$as_me:21796: result: $install_it" >&5
+  echo "$as_me:21806: result: $install_it" >&5
 echo "${ECHO_T}$install_it" >&6
   if test $install_it = "yes"; then
     TOPSUBDIRS="$TOPSUBDIRS $i"
@@ -21897,7 +21907,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:21900: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:21910: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -22073,7 +22083,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:22076: error: ambiguous option: $1
+    { { echo "$as_me:22086: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -22092,7 +22102,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:22095: error: unrecognized option: $1
+  -*) { { echo "$as_me:22105: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -22148,7 +22158,7 @@ do
   "sounds/Makefile" ) CONFIG_FILES="$CONFIG_FILES sounds/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:22151: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:22161: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -22502,7 +22512,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:22505: creating $ac_file" >&5
+    { echo "$as_me:22515: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -22520,7 +22530,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22523: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22533: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22533,7 +22543,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22536: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22546: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22594,7 +22604,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:22597: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:22607: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -22605,7 +22615,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22608: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22618: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22618,7 +22628,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22621: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22631: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22735,7 +22745,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:22738: $ac_file is unchanged" >&5
+      { echo "$as_me:22748: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
