Fix configure
git-svn-id: file:///.data/svn_convert/svn@8 f7a67266-ba00-4dfb-90a2-3eec4ba07b7d

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -22029,10 +22029,6 @@ done
 
 ac_config_files="$ac_config_files ./Makefile"
 
-ac_config_files="$ac_config_files doc/Makefile"
-
-ac_config_files="$ac_config_files doc/en/Makefile"
-
 ac_config_files="$ac_config_files po/Makefile"
 
 ac_config_files="$ac_config_files sim/Makefile"
@@ -22040,8 +22036,6 @@ ac_config_files="$ac_config_files sim/Makefile"
 ac_config_files="$ac_config_files sim/libicq/Makefile"
 
 ac_config_files="$ac_config_files sim/qt3/Makefile"
-
-ac_config_files="$ac_config_files sim/themes/Makefile"
 
 ac_config_files="$ac_config_files sim/ui/Makefile"
 
@@ -22126,7 +22120,7 @@ fi
 DEFS=-DHAVE_CONFIG_H
 
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
-  { { echo "$as_me:22129: error: conditional \"AMDEP\" was never defined.
+  { { echo "$as_me:22123: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
@@ -22136,7 +22130,7 @@ fi
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:22139: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:22133: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -22312,7 +22306,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:22315: error: ambiguous option: $1
+    { { echo "$as_me:22309: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -22331,7 +22325,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:22334: error: unrecognized option: $1
+  -*) { { echo "$as_me:22328: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -22376,19 +22370,16 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "./Makefile" ) CONFIG_FILES="$CONFIG_FILES ./Makefile" ;;
-  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
-  "doc/en/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/en/Makefile" ;;
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
   "sim/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/Makefile" ;;
   "sim/libicq/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/libicq/Makefile" ;;
   "sim/qt3/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/qt3/Makefile" ;;
-  "sim/themes/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/themes/Makefile" ;;
   "sim/ui/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/ui/Makefile" ;;
   "sim/xpm/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/xpm/Makefile" ;;
   "sounds/Makefile" ) CONFIG_FILES="$CONFIG_FILES sounds/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:22391: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:22382: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -22743,7 +22734,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:22746: creating $ac_file" >&5
+    { echo "$as_me:22737: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -22761,7 +22752,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22764: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22755: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22774,7 +22765,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22777: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22768: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22835,7 +22826,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:22838: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:22829: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -22846,7 +22837,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22849: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22840: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22859,7 +22850,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22862: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22853: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22976,7 +22967,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:22979: $ac_file is unchanged" >&5
+      { echo "$as_me:22970: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
