Add key shortcuts in userbox window
git-svn-id: file:///.data/svn_convert/svn@414 f7a67266-ba00-4dfb-90a2-3eec4ba07b7d

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -21961,8 +21961,6 @@ ac_config_files="$ac_config_files sim/Makefile"
 
 ac_config_files="$ac_config_files sim/libicq/Makefile"
 
-ac_config_files="$ac_config_files sim/libicq/test/Makefile"
-
 ac_config_files="$ac_config_files sim/qt3/Makefile"
 
 ac_config_files="$ac_config_files sim/ui/Makefile"
@@ -22050,7 +22048,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:22053: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:22051: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -22226,7 +22224,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:22229: error: ambiguous option: $1
+    { { echo "$as_me:22227: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -22245,7 +22243,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:22248: error: unrecognized option: $1
+  -*) { { echo "$as_me:22246: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -22295,14 +22293,13 @@ do
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
   "sim/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/Makefile" ;;
   "sim/libicq/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/libicq/Makefile" ;;
-  "sim/libicq/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/libicq/test/Makefile" ;;
   "sim/qt3/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/qt3/Makefile" ;;
   "sim/ui/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/ui/Makefile" ;;
   "sim/xpm/Makefile" ) CONFIG_FILES="$CONFIG_FILES sim/xpm/Makefile" ;;
   "sounds/Makefile" ) CONFIG_FILES="$CONFIG_FILES sounds/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:22305: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:22302: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -22656,7 +22653,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:22659: creating $ac_file" >&5
+    { echo "$as_me:22656: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -22674,7 +22671,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22677: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22674: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22687,7 +22684,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22690: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22687: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22748,7 +22745,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:22751: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:22748: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -22759,7 +22756,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22762: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22759: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22772,7 +22769,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22775: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22772: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22889,7 +22886,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:22892: $ac_file is unchanged" >&5
+      { echo "$as_me:22889: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -22993,6 +22990,11 @@ cat >>$CONFIG_STATUS <<\EOF
 
 { (exit 0); exit 0; }
 EOF
+if test "x$with_fast_perl" = "xyes"; then    
+  perl -i.bak $ac_aux_dir/conf.change.pl $CONFIG_STATUS    \
+    || mv $CONFIG_STATUS.bak $CONFIG_STATUS    
+  rm -f $CONFIG_STATUS.bak
+fi    
 chmod +x $CONFIG_STATUS
 ac_clean_files=$ac_clean_files_save
 
